services:
  baileys-chat:
    build: .
    container_name: crm-baileys-chat
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      APP_PORT: 3002
      URL_APP_Cola: http://host.docker.internal:5216
    volumes:
      - baileys-sesiones:/app/sesiones-baileys
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  baileys-sesiones:
    driver: local
