// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.WhatsappCola.Models;

/// <summary>
/// Almacena los mensajes salientes
/// </summary>
public partial class TMensajeCola
{
    /// <summary>
    /// Identificador de tabla
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Id del estado del mensaje, Fk con la tabla T_MensajeColaEstado
    /// </summary>
    public int IdMensajeColaEstado { get; set; }

    /// <summary>
    /// Número de la Cuenta de Whatsapp
    /// </summary>
    public string NumeroRemitente { get; set; }

    /// <summary>
    /// Número del Cliente
    /// </summary>
    public string NumeroDestino { get; set; }

    /// <summary>
    /// Texto del mensaje
    /// </summary>
    public string Mensaje { get; set; }

    /// <summary>
    /// Archivo adjunto en base64
    /// </summary>
    public string AdjuntoBase64 { get; set; }

    /// <summary>
    /// Nombre del archivo adjunto
    /// </summary>
    public string NombreArchivo { get; set; }

    /// <summary>
    /// Mimetype del archivo adjunto
    /// </summary>
    public string MimeType { get; set; }

    /// <summary>
    /// Nro. de bytes del archivo adjunto
    /// </summary>
    public int? NroByte { get; set; }

    /// <summary>
    /// Url del archivo
    /// </summary>
    public string UrlArchivo { get; set; }

    /// <summary>
    /// Estado del elemento
    /// </summary>
    public bool Estado { get; set; }

    /// <summary>
    /// Usuario de creacion del registro
    /// </summary>
    public string UsuarioCreacion { get; set; }

    /// <summary>
    /// Usuario de modificacion del registro
    /// </summary>
    public string UsuarioModificacion { get; set; }

    /// <summary>
    /// Fecha de creacion del registro
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Fecha de modificacion del registro
    /// </summary>
    public DateTime FechaModificacion { get; set; }

    /// <summary>
    /// Mensaje de error al enviar el mensaje
    /// </summary>
    public string Error { get; set; }

    /// <summary>
    /// Fecha de envío del mensaje
    /// </summary>
    public DateTime? FechaEnvio { get; set; }

    /// <summary>
    /// Identificador del mensaje en WhatsApp
    /// </summary>
    public string WhatsAppId { get; set; }

    public int AckEstado { get; set; }

    public virtual TMensajeColaEstado IdMensajeColaEstadoNavigation { get; set; }
}