// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.WhatsappCola.Models;

/// <summary>
/// Almacena los mensajes entrantes
/// </summary>
public partial class TMensajeEntrante
{
    /// <summary>
    /// Identificador de tabla
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Estado del mensaje, Fk con la tabla T_MensajeEntranteEstado
    /// </summary>
    public int IdMensajeEntranteEstado { get; set; }

    /// <summary>
    /// Numero de la cuenta de whatsaap
    /// </summary>
    public string NumeroCuenta { get; set; }

    /// <summary>
    /// Numero del cliente
    /// </summary>
    public string NumeroCliente { get; set; }

    /// <summary>
    /// Tipo de mensaje en WhatsApp
    /// </summary>
    public string WhatsAppTipo { get; set; }

    /// <summary>
    /// Identiticador del emnsaje en WhatsApp
    /// </summary>
    public string WhatsAppId { get; set; }

    /// <summary>
    /// Fecha de envío del mensaje
    /// </summary>
    public DateTime FechaEnvio { get; set; }

    /// <summary>
    /// Texto del mensaje
    /// </summary>
    public string Mensaje { get; set; }

    /// <summary>
    /// Indica si el mensaje tiene adjuntos
    /// </summary>
    public bool? TieneAdjunto { get; set; }

    /// <summary>
    /// Archivo adjunto en base 64
    /// </summary>
    public string AdjuntoBase64 { get; set; }

    /// <summary>
    /// Nombre del archivo adjunto
    /// </summary>
    public string NombreArchivo { get; set; }

    /// <summary>
    /// Mimetype del archivo adjunto
    /// </summary>
    public string MimeType { get; set; }

    /// <summary>
    /// Nro. de Bytes del archivo adjunto
    /// </summary>
    public int? NroByte { get; set; }

    /// <summary>
    /// Url del Archivo
    /// </summary>
    public string UrlArchivo { get; set; }

    /// <summary>
    /// Estado del elemento
    /// </summary>
    public bool Estado { get; set; }

    /// <summary>
    /// Usuario de creacion del registro
    /// </summary>
    public string UsuarioCreacion { get; set; }

    /// <summary>
    /// Usuario de modificacion del registro
    /// </summary>
    public string UsuarioModificacion { get; set; }

    /// <summary>
    /// Fecha de creacion del registro
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Fecha de modificacion del registro
    /// </summary>
    public DateTime FechaModificacion { get; set; }

    /// <summary>
    /// Identificador del mensaje padre en WhatsApp
    /// </summary>
    public string WhatsAppIdPadre { get; set; }

    /// <summary>
    /// Id del mensaje padre en la tabla T_MensajeEntrante
    /// </summary>
    public int? IdMensajeEntrantePadre { get; set; }

    /// <summary>
    /// Id del mensaje padre en la tabla T_MensajeCola
    /// </summary>
    public int? IdMensajeColaPadre { get; set; }

    /// <summary>
    /// Indica si el mensaje fue eliminado
    /// </summary>
    public bool? FueEliminado { get; set; }

    /// <summary>
    /// Fecha en la que se recibio el mensaje de eliminacion
    /// </summary>
    public DateTime? FechaRecepcionEliminacion { get; set; }

    /// <summary>
    /// Indica si al descargar el archivo multimedia hubo error
    /// </summary>
    public bool? EsErrorDescargaMultimedia { get; set; }

    /// <summary>
    /// Nombre del contacto que envío el mensaje
    /// </summary>
    public string NombreContacto { get; set; }

    public virtual TMensajeEntranteEstado IdMensajeEntranteEstadoNavigation { get; set; }
}