// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.WhatsappCola.Models;

public partial class TTipoMensaje
{
    /// <summary>
    /// Identificador de tabla
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Indica el Tipo de Mensaje
    /// </summary>
    public string Nombre { get; set; }

    /// <summary>
    /// Estado del elemento
    /// </summary>
    public bool Estado { get; set; }

    /// <summary>
    /// Usuario de creacion del registro
    /// </summary>
    public string UsuarioCreacion { get; set; }

    /// <summary>
    /// Usuario de modificacion del registro
    /// </summary>
    public string UsuarioModificacion { get; set; }

    /// <summary>
    /// Fecha de creacion del registro
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Fecha de modificacion del registro
    /// </summary>
    public DateTime FechaModificacion { get; set; }
}