// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.WhatsappCola.Models;

/// <summary>
/// Almacena la lista de usuarios
/// </summary>
public partial class TUsuario
{
    /// <summary>
    /// Identificador de tabla
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Nombres
    /// </summary>
    public string Nombres { get; set; }

    /// <summary>
    /// Apellido Paterno
    /// </summary>
    public string ApellidoPaterno { get; set; }

    /// <summary>
    /// Apellido Materno
    /// </summary>
    public string ApellidoMaterno { get; set; }

    /// <summary>
    /// Nombre del usuario
    /// </summary>
    public string NombreUsuario { get; set; }

    /// <summary>
    /// Clave hash del usuario
    /// </summary>
    public string ClaveHash { get; set; }

    /// <summary>
    /// Estado del elemento
    /// </summary>
    public bool Estado { get; set; }

    /// <summary>
    /// Usuario de creacion del registro
    /// </summary>
    public string UsuarioCreacion { get; set; }

    /// <summary>
    /// Usuario de modificacion del registro
    /// </summary>
    public string UsuarioModificacion { get; set; }

    /// <summary>
    /// Fecha de creacion del registro
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Fecha de modificacion del registro
    /// </summary>
    public DateTime FechaModificacion { get; set; }
}