// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.WhatsappCola.Models;

public partial class VObtenerResumenConversacion
{
    public string NumeroCuenta { get; set; }

    public string NumeroCliente { get; set; }

    public DateTime? FechaUltimoMensaje { get; set; }

    public string NombreContacto { get; set; }
}