// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.WhatsappCola.Models;

public partial class VObtenerDetalleMensajes
{
    public int? IdMensajeSaliente { get; set; }

    public int? IdMensajeEntrante { get; set; }

    public string NumeroCuenta { get; set; }

    public string NumeroCliente { get; set; }

    public DateOnly? Fecha { get; set; }

    public DateTime? FechaEnvio { get; set; }

    public string WhatsAppId { get; set; }

    public string Mensaje { get; set; }

    public string WhatsAppIdPadre { get; set; }

    public int? IdMensajeSalientePadre { get; set; }

    public int? IdMensajeEntrantePadre { get; set; }

    public string Error { get; set; }

    public string MimeType { get; set; }

    public string AdjuntoBase64 { get; set; }

    public string NombreArchivo { get; set; }

    public bool? EsErrorDescargaMultimedia { get; set; }

    public int? AckEstado { get; set; }
}