// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CRM.WhatsappCola.Models;

public partial class WA_ColaContext : DbContext
{
    public WA_ColaContext(DbContextOptions<WA_ColaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TConversacion> TConversacion { get; set; }

    public virtual DbSet<TMensajeCola> TMensajeCola { get; set; }

    public virtual DbSet<TMensajeColaEstado> TMensajeColaEstado { get; set; }

    public virtual DbSet<TMensajeEntrante> TMensajeEntrante { get; set; }

    public virtual DbSet<TMensajeEntranteEstado> TMensajeEntranteEstado { get; set; }

    public virtual DbSet<TTipoMensaje> TTipoMensaje { get; set; }

    public virtual DbSet<TUsuario> TUsuario { get; set; }

    public virtual DbSet<VObtenerDetalleMensajes> VObtenerDetalleMensajes { get; set; }

    public virtual DbSet<VObtenerResumenConversacion> VObtenerResumenConversacion { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TConversacion>(entity =>
        {
            entity.ToTable("T_Conversacion");

            entity.Property(e => e.Id).HasComment("Identificador de tabla");
            entity.Property(e => e.Estado).HasComment("Estado del elemento");
            entity.Property(e => e.FechaCreacion)
                .HasComment("Fecha de creacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion)
                .HasComment("Fecha de modificacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.NumeroCliente)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComment("Numero del cliente");
            entity.Property(e => e.NumeroCuenta)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComment("Numero de la cuenta de whatsaap");
            entity.Property(e => e.UsuarioCreacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de creacion del registro");
            entity.Property(e => e.UsuarioModificacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de modificacion del registro");
        });

        modelBuilder.Entity<TMensajeCola>(entity =>
        {
            entity.ToTable("T_MensajeCola", tb => tb.HasComment("Almacena los mensajes salientes"));

            entity.Property(e => e.Id).HasComment("Identificador de tabla");
            entity.Property(e => e.AdjuntoBase64).HasComment("Archivo adjunto en base64");
            entity.Property(e => e.Error).HasComment("Mensaje de error al enviar el mensaje");
            entity.Property(e => e.Estado).HasComment("Estado del elemento");
            entity.Property(e => e.FechaCreacion)
                .HasComment("Fecha de creacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaEnvio)
                .HasComment("Fecha de envío del mensaje")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion)
                .HasComment("Fecha de modificacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.IdMensajeColaEstado).HasComment("Id del estado del mensaje, Fk con la tabla T_MensajeColaEstado");
            entity.Property(e => e.Mensaje).HasComment("Texto del mensaje");
            entity.Property(e => e.MimeType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Mimetype del archivo adjunto");
            entity.Property(e => e.NombreArchivo)
                .HasMaxLength(1024)
                .HasComment("Nombre del archivo adjunto");
            entity.Property(e => e.NroByte).HasComment("Nro. de bytes del archivo adjunto");
            entity.Property(e => e.NumeroDestino)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasComment("Número del Cliente");
            entity.Property(e => e.NumeroRemitente)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasComment("Número de la Cuenta de Whatsapp");
            entity.Property(e => e.UrlArchivo)
                .IsUnicode(false)
                .HasComment("Url del archivo");
            entity.Property(e => e.UsuarioCreacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de creacion del registro");
            entity.Property(e => e.UsuarioModificacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de modificacion del registro");
            entity.Property(e => e.WhatsAppId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Identificador del mensaje en WhatsApp");

            entity.HasOne(d => d.IdMensajeColaEstadoNavigation).WithMany(p => p.TMensajeCola)
                .HasForeignKey(d => d.IdMensajeColaEstado)
                .HasConstraintName("FK_T_MensajeCola_T_MensajeColaEstado");
        });

        modelBuilder.Entity<TMensajeColaEstado>(entity =>
        {
            entity.ToTable("T_MensajeColaEstado", tb => tb.HasComment("Almacena el estado de los mensajes Salientes"));

            entity.Property(e => e.Id).HasComment("Identificador de tabla");
            entity.Property(e => e.Estado).HasComment("Estado del elemento");
            entity.Property(e => e.FechaCreacion)
                .HasComment("Fecha de creacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion)
                .HasComment("Fecha de modificacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Nombre del estado");
            entity.Property(e => e.UsuarioCreacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de creacion del registro");
            entity.Property(e => e.UsuarioModificacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de modificacion del registro");
        });

        modelBuilder.Entity<TMensajeEntrante>(entity =>
        {
            entity.ToTable("T_MensajeEntrante", tb => tb.HasComment("Almacena los mensajes entrantes"));

            entity.Property(e => e.Id).HasComment("Identificador de tabla");
            entity.Property(e => e.AdjuntoBase64).HasComment("Archivo adjunto en base 64");
            entity.Property(e => e.EsErrorDescargaMultimedia).HasComment("Indica si al descargar el archivo multimedia hubo error");
            entity.Property(e => e.Estado).HasComment("Estado del elemento");
            entity.Property(e => e.FechaCreacion)
                .HasComment("Fecha de creacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaEnvio)
                .HasComment("Fecha de envío del mensaje")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion)
                .HasComment("Fecha de modificacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaRecepcionEliminacion)
                .HasComment("Fecha en la que se recibio el mensaje de eliminacion")
                .HasColumnType("datetime");
            entity.Property(e => e.FueEliminado).HasComment("Indica si el mensaje fue eliminado");
            entity.Property(e => e.IdMensajeColaPadre).HasComment("Id del mensaje padre en la tabla T_MensajeCola");
            entity.Property(e => e.IdMensajeEntranteEstado).HasComment("Estado del mensaje, Fk con la tabla T_MensajeEntranteEstado");
            entity.Property(e => e.IdMensajeEntrantePadre).HasComment("Id del mensaje padre en la tabla T_MensajeEntrante");
            entity.Property(e => e.Mensaje).HasComment("Texto del mensaje");
            entity.Property(e => e.MimeType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Mimetype del archivo adjunto");
            entity.Property(e => e.NombreArchivo)
                .HasMaxLength(1024)
                .HasComment("Nombre del archivo adjunto");
            entity.Property(e => e.NombreContacto)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasComment("Nombre del contacto que envío el mensaje");
            entity.Property(e => e.NroByte).HasComment("Nro. de Bytes del archivo adjunto");
            entity.Property(e => e.NumeroCliente)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComment("Numero del cliente");
            entity.Property(e => e.NumeroCuenta)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasComment("Numero de la cuenta de whatsaap");
            entity.Property(e => e.TieneAdjunto).HasComment("Indica si el mensaje tiene adjuntos");
            entity.Property(e => e.UrlArchivo).HasComment("Url del Archivo");
            entity.Property(e => e.UsuarioCreacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de creacion del registro");
            entity.Property(e => e.UsuarioModificacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de modificacion del registro");
            entity.Property(e => e.WhatsAppId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Identiticador del emnsaje en WhatsApp");
            entity.Property(e => e.WhatsAppIdPadre)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Identificador del mensaje padre en WhatsApp");
            entity.Property(e => e.WhatsAppTipo)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasComment("Tipo de mensaje en WhatsApp");

            entity.HasOne(d => d.IdMensajeEntranteEstadoNavigation).WithMany(p => p.TMensajeEntrante)
                .HasForeignKey(d => d.IdMensajeEntranteEstado)
                .HasConstraintName("FK_T_MensajeEntrante_T_MensajeEntranteEstado");
        });

        modelBuilder.Entity<TMensajeEntranteEstado>(entity =>
        {
            entity.ToTable("T_MensajeEntranteEstado", tb => tb.HasComment("Almacena el estado de los mensajes Entrantes"));

            entity.Property(e => e.Id).HasComment("Identificador de tabla");
            entity.Property(e => e.Estado).HasComment("Estado del elemento");
            entity.Property(e => e.FechaCreacion)
                .HasComment("Fecha de creacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion)
                .HasComment("Fecha de modificacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UsuarioCreacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de creacion del registro");
            entity.Property(e => e.UsuarioModificacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de modificacion del registro");
        });

        modelBuilder.Entity<TTipoMensaje>(entity =>
        {
            entity.ToTable("T_TipoMensaje");

            entity.Property(e => e.Id).HasComment("Identificador de tabla");
            entity.Property(e => e.Estado).HasComment("Estado del elemento");
            entity.Property(e => e.FechaCreacion)
                .HasComment("Fecha de creacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion)
                .HasComment("Fecha de modificacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Indica el Tipo de Mensaje");
            entity.Property(e => e.UsuarioCreacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de creacion del registro");
            entity.Property(e => e.UsuarioModificacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de modificacion del registro");
        });

        modelBuilder.Entity<TUsuario>(entity =>
        {
            entity.ToTable("T_Usuario", tb => tb.HasComment("Almacena la lista de usuarios"));

            entity.HasIndex(e => e.NombreUsuario, "UC_T_Usuario_NombreUsuario").IsUnique();

            entity.Property(e => e.Id).HasComment("Identificador de tabla");
            entity.Property(e => e.ApellidoMaterno)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasComment("Apellido Materno");
            entity.Property(e => e.ApellidoPaterno)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasComment("Apellido Paterno");
            entity.Property(e => e.ClaveHash)
                .IsRequired()
                .HasMaxLength(512)
                .IsUnicode(false)
                .HasComment("Clave hash del usuario");
            entity.Property(e => e.Estado).HasComment("Estado del elemento");
            entity.Property(e => e.FechaCreacion)
                .HasComment("Fecha de creacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion)
                .HasComment("Fecha de modificacion del registro")
                .HasColumnType("datetime");
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Nombre del usuario");
            entity.Property(e => e.Nombres)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasComment("Nombres");
            entity.Property(e => e.UsuarioCreacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de creacion del registro");
            entity.Property(e => e.UsuarioModificacion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Usuario de modificacion del registro");
        });

        modelBuilder.Entity<VObtenerDetalleMensajes>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("V_Obtener_DetalleMensajes");

            entity.Property(e => e.FechaEnvio).HasColumnType("datetime");
            entity.Property(e => e.MimeType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NombreArchivo).HasMaxLength(500);
            entity.Property(e => e.NumeroCliente)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.NumeroCuenta)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.WhatsAppId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.WhatsAppIdPadre)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VObtenerResumenConversacion>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("V_Obtener_ResumenConversacion");

            entity.Property(e => e.FechaUltimoMensaje).HasColumnType("datetime");
            entity.Property(e => e.NombreContacto)
                .IsRequired()
                .HasMaxLength(256)
                .IsUnicode(false);
            entity.Property(e => e.NumeroCliente)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.NumeroCuenta)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}